### ISSUE TITLE
How could we use this package?

### ISSUE THREAD

**Issue by ashankasr** [Inoverse/ngx-fs#1]
No demo code is available

**Comment by aaronczichon** [comment]
There is demo code available. See [`Readme.md`](https://github.com/Inoverse/ngx-fs/blob/master/README.md)

**Comment by ashankasr** [comment]
Thank you for your quick response but Readme.md only explain how you should configure the FsService.

Could you please explain how should I use to read a file using _fsService?

**Comment by aaronczichon** [comment]
Use the same API as on NodeJS documentation described.
